In [ ]:
import pandas as pd

# Reemplaza 'archivo.csv' con el nombre o la ruta de tu archivo CSV
df = pd.read_csv('mi_archivo.csv', encoding='utf-8')  # Usa encoding='latin1' si tienes caracteres especiales

# Verifica las primeras filas
print(df.head())
# comentario

        RUT DV_x  COD_SUBTIPO                              RAZON_SOCIAL  \
0  50032710    3          211  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA
1  50032710    3          211  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA
2  50032710    3          211  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA
3  50032710    3          211  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA
4  50032710    3          211  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA

  FECHA_INICIO_VIG FECHA_TG_VIG  AÃ±o_comercial DV_y  \
0       01-01-1993          NaN           2005    3
1       01-01-1993          NaN           2006    3
2       01-01-1993          NaN           2007    3
3       01-01-1993          NaN           2008    3
4       01-01-1993          NaN           2009    3

                               Razon_social  Tramo_segun_ventas  ...  \
0  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA                   7  ...
1  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA                   7  ...
2  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA                   7  ...
3  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA                   7  ...
4  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA                   7  ...

   Tramo_capital_propio_positivo Tramo_capital_propio_negativo  \
0                            9.0                           NaN
1                            9.0                           NaN
2                            8.0                           NaN
3                            9.0                           NaN
4                            9.0                           NaN

                Rubro_economico  \
0  INFORMACION Y COMUNICACIONES
1  INFORMACION Y COMUNICACIONES
2  INFORMACION Y COMUNICACIONES
3  INFORMACION Y COMUNICACIONES
4  INFORMACION Y COMUNICACIONES

                                  Subrubro_economico Actividad_economica  \
0  EDICION DE LIBROS Y PUBLICACIONES PERIODICAS Y...   EDICION DE LIBROS
1  EDICION DE LIBROS Y PUBLICACIONES PERIODICAS Y...   EDICION DE LIBROS
2  EDICION DE LIBROS Y PUBLICACIONES PERIODICAS Y...   EDICION DE LIBROS
3  EDICION DE LIBROS Y PUBLICACIONES PERIODICAS Y...   EDICION DE LIBROS
4  EDICION DE LIBROS Y PUBLICACIONES PERIODICAS Y...   EDICION DE LIBROS

                      Region Provincia       Comuna  R_PRESUNTA  \
0  XIII REGION METROPOLITANA  Santiago  PROVIDENCIA         NaN
1  XIII REGION METROPOLITANA  Santiago  PROVIDENCIA         NaN
2  XIII REGION METROPOLITANA  Santiago  PROVIDENCIA         NaN
3  XIII REGION METROPOLITANA  Santiago  PROVIDENCIA         NaN
4  XIII REGION METROPOLITANA  Santiago  PROVIDENCIA         NaN

  OTROS_REGIMENES
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN

[5 rows x 27 columns]

In [3]:
# Asegura que estas columnas sean numÃ©ricas o convertibles si aplica
df['Anno_comercial'] = pd.to_numeric(df['AÃ±o_comercial'], errors='coerce')
df['Numero_trabajadores_dependientes'] = pd.to_numeric(df['Numero_trabajadores_dependientes'], errors='coerce')
df['Tramo_segun_ventas'] = pd.to_numeric(df['Tramo_segun_ventas'], errors='coerce')  # Solo si son valores numÃ©ricos

# Columnas informativas (las que se mantienen como 'first')
columnas_informativas = [
    'DV_x', 'COD_SUBTIPO', 'RAZON_SOCIAL', 'FECHA_INICIO_VIG',
    'FECHA_TG_VIG', 'DV_y', 'Razon_social',
    'Fecha_inicio_actividades_vigente', 'Fecha_termino_giro',
    'Fecha_primera_inscripcion_ac', 'Tipo_termino_giro',
    'Tipo_contribuyente', 'Subtipo_contribuyente'
]

# Diccionario de agregaciÃ³n
agg_dict = {col: 'first' for col in columnas_informativas}
agg_dict.update({
    'Anno_comercial': ['min', 'max'],
    'Numero_trabajadores_dependientes': ['min', 'max'],
    'Tramo_segun_ventas': ['min', 'max']
})

# Aplicar agrupamiento
agrupado = df.groupby('RUT').agg(agg_dict)

# Aplanar columnas
agrupado.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in agrupado.columns]

# Renombrar columnas para mayor claridad
agrupado = agrupado.rename(columns={
    'Anno_comercial_min': 'Anno_min',
    'Anno_comercial_max': 'Anno_max',
    'Numero_trabajadores_dependientes_min': 'Trabajadores_min',
    'Numero_trabajadores_dependientes_max': 'Trabajadores_max',
    'Tramo_segun_ventas_min': 'Ventas_min',
    'Tramo_segun_ventas_max': 'Ventas_max'
})

# Calcular nÃºmero de aÃ±os
agrupado['Numero_de_annos'] = agrupado['Anno_max'] - agrupado['Anno_min'] + 1

# Reset index
agrupado = agrupado.reset_index()

# Mostrar resultado
print(agrupado)

             RUT DV_x_first  COD_SUBTIPO_first  \
0       47003012          7                414
1       47003969          8                414
2       50000100          3                311
3       50000430          4                311
4       50000510          6                311
...          ...        ...                ...
360227  99599800          9                213
360228  99599810          6                213
360229  99599830          0                213
360230  99599850          5                213
360231  99599860          2                213

                            RAZON_SOCIAL_first FECHA_INICIO_VIG_first  \
0                  TACONIC  OPPORTUITY FUND LP                   None
1               RUT CUSTODIO LARRAIN VIAL S A.                   None
2          FUNDACION ARTURO IRARRAZAVAL CORREA             01-01-1993
3          SAAVEDRA GALLARDO JAVIER Y HERMANOS             01-01-1993
4                  TORREJON CASTRO LUIS Y JOSE             01-01-1993
...                                        ...                    ...
360227                  AUTOMOTRIZ P.G CAR S.A                   None
360228  COMPANIA DE TRANSPORTES INTEGRADOS S A                   None
360229   INMOBILIARIA E INVERSIONES PUCARA S A                   None
360230                SOLUCIONES ABIERTAS  S A             01-07-2005
360231                                ORAND SA             01-07-2005

       FECHA_TG_VIG_first DV_y_first                      Razon_social_first  \
0                    None          7             TACONIC  OPPORTUITY FUND LP
1                    None          8          RUT CUSTODIO LARRAIN VIAL S A.
2                    None          3     FUNDACION ARTURO IRARRAZAVAL CORREA
3                    None          4     SAAVEDRA GALLARDO JAVIER Y HERMANOS
4                    None          6             TORREJON CASTRO LUIS Y JOSE
...                   ...        ...                                     ...
360227         28-12-2016          9                  AUTOMOTRIZ P.G CAR S.A
360228         30-01-2017          6  COMPANIA DE TRANSPORTES INTEGRADOS S A
360229         17-02-2016          0   INMOBILIARIA E INVERSIONES PUCARA S A
360230               None          5                SOLUCIONES ABIERTAS  S A
360231               None          2                                ORAND SA

       Fecha_inicio_actividades_vigente_first Fecha_termino_giro_first  ...  \
0                                        None                     None  ...
1                                        None                     None  ...
2                                  1993-01-01                     None  ...
3                                  1993-01-01                     None  ...
4                                  1993-01-01                     None  ...
...                                       ...                      ...  ...
360227                                   None               2016-12-28  ...
360228                                   None               2017-01-30  ...
360229                                   None               2016-02-17  ...
360230                             2005-07-01                     None  ...
360231                             2005-07-01                     None  ...

                 Tipo_termino_giro_first    Tipo_contribuyente_first  \
0                                   None      SOCIEDADES EXTRANJERAS
1                                   None      SOCIEDADES EXTRANJERAS
2                                   None           SIN PER. JURIDICA
3                                   None           SIN PER. JURIDICA
4                                   None           SIN PER. JURIDICA
...                                  ...                         ...
360227  TERMINO DE GIRO PERSONA JURIDICA  PERSONA JURIDICA COMERCIAL
360228  TERMINO DE GIRO PERSONA JURIDICA  PERSONA JURIDICA COMERCIAL
360229  TERMINO DE GIRO PERSONA JURIDICA  PERSONA JURIDICA COMERCIAL
360230                              None  PERSONA JURIDICA COMERCIAL
360231                              None  PERSONA JURIDICA COMERCIAL

              Subtipo_contribuyente_first Anno_min  Anno_max  \
0       SOCIEDAD EXTRANJERA RES 5412/2000     2009      2009
1       SOCIEDAD EXTRANJERA RES 5412/2000     2008      2008
2                     SOCIEDADES DE HECHO     2005      2009
3                     SOCIEDADES DE HECHO     2005      2008
4                     SOCIEDADES DE HECHO     2005      2009
...                                   ...      ...       ...
360227       SOCIEDADES ANONIMAS CERRADAS     2005      2007
360228       SOCIEDADES ANONIMAS CERRADAS     2005      2009
360229       SOCIEDADES ANONIMAS CERRADAS     2009      2009
360230       SOCIEDADES ANONIMAS CERRADAS     2005      2006
360231       SOCIEDADES ANONIMAS CERRADAS     2005      2009

        Trabajadores_min  Trabajadores_max  Ventas_min  Ventas_max  \
0                      0                 0           1           1
1                      0                 0           1           1
2                      5                 7           1           1
3                      0                 0           2           3
4                      0                 1           6           6
...                  ...               ...         ...         ...
360227                 3                 6           2           4
360228                 0                 0           6           7
360229                 0                 0           1           1
360230                12                14           4           5
360231                 5                20           5           7

        Numero_de_annos
0                     1
1                     1
2                     5
3                     4
4                     5
...                 ...
360227                3
360228                5
360229                1
360230                2
360231                5

[360232 rows x 21 columns]

In [13]:
print(agrupado.columns)
print(agrupado)

Index(['RUT', 'DV_x_first', 'COD_SUBTIPO_first', 'RAZON_SOCIAL_first',
       'FECHA_INICIO_VIG_first', 'FECHA_TG_VIG_first', 'DV_y_first',
       'Razon_social_first', 'Fecha_inicio_actividades_vigente_first',
       'Fecha_termino_giro_first', 'Fecha_primera_inscripcion_ac_first',
       'Tipo_termino_giro_first', 'Tipo_contribuyente_first',
       'Subtipo_contribuyente_first', 'Anno_min', 'Anno_max',
       'Trabajadores_min', 'Trabajadores_max', 'Ventas_min', 'Ventas_max',
       'Numero_de_annos'],
      dtype='object')
             RUT DV_x_first  COD_SUBTIPO_first  \
0       47003012          7                414
1       47003969          8                414
2       50000100          3                311
3       50000430          4                311
4       50000510          6                311
...          ...        ...                ...
360227  99599800          9                213
360228  99599810          6                213
360229  99599830          0                213
360230  99599850          5                213
360231  99599860          2                213

                            RAZON_SOCIAL_first FECHA_INICIO_VIG_first  \
0                  TACONIC  OPPORTUITY FUND LP                   None
1               RUT CUSTODIO LARRAIN VIAL S A.                   None
2          FUNDACION ARTURO IRARRAZAVAL CORREA             01-01-1993
3          SAAVEDRA GALLARDO JAVIER Y HERMANOS             01-01-1993
4                  TORREJON CASTRO LUIS Y JOSE             01-01-1993
...                                        ...                    ...
360227                  AUTOMOTRIZ P.G CAR S.A                   None
360228  COMPANIA DE TRANSPORTES INTEGRADOS S A                   None
360229   INMOBILIARIA E INVERSIONES PUCARA S A                   None
360230                SOLUCIONES ABIERTAS  S A             01-07-2005
360231                                ORAND SA             01-07-2005

       FECHA_TG_VIG_first DV_y_first                      Razon_social_first  \
0                    None          7             TACONIC  OPPORTUITY FUND LP
1                    None          8          RUT CUSTODIO LARRAIN VIAL S A.
2                    None          3     FUNDACION ARTURO IRARRAZAVAL CORREA
3                    None          4     SAAVEDRA GALLARDO JAVIER Y HERMANOS
4                    None          6             TORREJON CASTRO LUIS Y JOSE
...                   ...        ...                                     ...
360227         28-12-2016          9                  AUTOMOTRIZ P.G CAR S.A
360228         30-01-2017          6  COMPANIA DE TRANSPORTES INTEGRADOS S A
360229         17-02-2016          0   INMOBILIARIA E INVERSIONES PUCARA S A
360230               None          5                SOLUCIONES ABIERTAS  S A
360231               None          2                                ORAND SA

       Fecha_inicio_actividades_vigente_first Fecha_termino_giro_first  ...  \
0                                        None                     None  ...
1                                        None                     None  ...
2                                  1993-01-01                     None  ...
3                                  1993-01-01                     None  ...
4                                  1993-01-01                     None  ...
...                                       ...                      ...  ...
360227                                   None               2016-12-28  ...
360228                                   None               2017-01-30  ...
360229                                   None               2016-02-17  ...
360230                             2005-07-01                     None  ...
360231                             2005-07-01                     None  ...

                 Tipo_termino_giro_first    Tipo_contribuyente_first  \
0                                   None      SOCIEDADES EXTRANJERAS
1                                   None      SOCIEDADES EXTRANJERAS
2                                   None           SIN PER. JURIDICA
3                                   None           SIN PER. JURIDICA
4                                   None           SIN PER. JURIDICA
...                                  ...                         ...
360227  TERMINO DE GIRO PERSONA JURIDICA  PERSONA JURIDICA COMERCIAL
360228  TERMINO DE GIRO PERSONA JURIDICA  PERSONA JURIDICA COMERCIAL
360229  TERMINO DE GIRO PERSONA JURIDICA  PERSONA JURIDICA COMERCIAL
360230                              None  PERSONA JURIDICA COMERCIAL
360231                              None  PERSONA JURIDICA COMERCIAL

              Subtipo_contribuyente_first Anno_min  Anno_max  \
0       SOCIEDAD EXTRANJERA RES 5412/2000     2009      2009
1       SOCIEDAD EXTRANJERA RES 5412/2000     2008      2008
2                     SOCIEDADES DE HECHO     2005      2009
3                     SOCIEDADES DE HECHO     2005      2008
4                     SOCIEDADES DE HECHO     2005      2009
...                                   ...      ...       ...
360227       SOCIEDADES ANONIMAS CERRADAS     2005      2007
360228       SOCIEDADES ANONIMAS CERRADAS     2005      2009
360229       SOCIEDADES ANONIMAS CERRADAS     2009      2009
360230       SOCIEDADES ANONIMAS CERRADAS     2005      2006
360231       SOCIEDADES ANONIMAS CERRADAS     2005      2009

        Trabajadores_min  Trabajadores_max  Ventas_min  Ventas_max  \
0                      0                 0           1           1
1                      0                 0           1           1
2                      5                 7           1           1
3                      0                 0           2           3
4                      0                 1           6           6
...                  ...               ...         ...         ...
360227                 3                 6           2           4
360228                 0                 0           6           7
360229                 0                 0           1           1
360230                12                14           4           5
360231                 5                20           5           7

        Numero_de_annos
0                     1
1                     1
2                     5
3                     4
4                     5
...                 ...
360227                3
360228                5
360229                1
360230                2
360231                5

[360232 rows x 21 columns]

In [15]:
# Por ejemplo, si quieres filtrar el RUT '12345678-9'
rut_especifico = 50032710

df_rut = agrupado[agrupado['RUT'] == rut_especifico]

# Ver las primeras filas del resultado
print(df_rut.head())

         RUT DV_x_first  COD_SUBTIPO_first  \
91  50032710          3                211

                          RAZON_SOCIAL_first FECHA_INICIO_VIG_first  \
91  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA             01-01-1993

   FECHA_TG_VIG_first DV_y_first                        Razon_social_first  \
91               None          3  CENTRO DE PERFECCIONAMIENTO TECNICO LTDA

   Fecha_inicio_actividades_vigente_first Fecha_termino_giro_first  ...  \
91                             1993-01-01                     None  ...

   Tipo_termino_giro_first    Tipo_contribuyente_first  \
91                    None  PERSONA JURIDICA COMERCIAL

      Subtipo_contribuyente_first Anno_min  Anno_max  Trabajadores_min  \
91  SOC. RESPONSABILIDAD LIMITADA     2005      2009                21

    Trabajadores_max  Ventas_min  Ventas_max  Numero_de_annos
91                33           7           7                5

[1 rows x 21 columns]